port: 2424
admin_port: 2525
log:
  level: "info"
rate_limiter:
  enabled: false
  num_requests: 200
request_limits:
  allow_setting_keys: false
  max_size_bytes: 100000
  max_num_values: 200
  max_ttl_seconds: 7200
backend:
  type: "redis" # Can also be "aerospike", "azure", "cassandra", "memcache" or "redis"
  aerospike:
    host: "aerospike.prebid.com"
    port: 3000
    namespace: "whatever"
  azure:
    account: "azure-account-here"
    key: "azure-key-here"
  cassandra:
    hosts: "127.0.0.1"
    keyspace: "prebid"
  memcache:
    hosts: "10.0.0.1:11211" # Can also use an array for multiple hosts
  redis:
    host: "host.docker.internal"
    port: 6379
    # password: "97383"
    db: 1
    tls:
      enabled: false
      insecure_skip_verify: true
compression:
  type: "none" # Can also be "none", "snappy"
metrics:
  type: "none" # Can also be "influx"
  influx:
    host: "https://eu-central-1-1.aws.cloud2.influxdata.com"
    database: "test"
    username: "3aba26e4e85d75e8"
    password: "6fbhYY@XcheVMU4"
routes:
  allow_public_write: true
