port: 2424
admin_port: 2525
index_response: "Goldlayer - prebid cache"
log:
  level: "info"
rate_limiter:
  enabled: false
  num_requests: 1200
request_limits:
  allow_setting_keys: true
  max_size_bytes: 200000
  max_num_values: 40000
  max_ttl_seconds: 3600
backend:
  type: "redis"
  redis:
    host: "host.docker.internal"
    port: 6379
    db: 1
    tls:
      enabled: false
      insecure_skip_verify: true
compression:
  type: "none"
metrics:
  type: "none"
routes:
  allow_public_write: true
