name: Validate Merge

on:
  pull_request:
    branches: [master]

jobs:
  validate-merge:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19.5

    - name: Checkout Merged Branch
      uses: actions/checkout@v3

    - name: Validate
      run: |
        ./validate.sh --nofmt
      env:
        GO111MODULE: "on"
